In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("cohort_index_dataset.csv")

In [5]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'Year', 'Month', 'Day', 'Day_Name',
       'First_Purchase_Date', 'Cohort_Month', 'Order_Month', 'Revenue',
       'Cohort_Index'],
      dtype='object')

In [7]:
df[["Customer ID","Cohort_Month","Order_Month","Cohort_Index"]].head(10)

   Customer ID Cohort_Month Order_Month  Cohort_Index
0      13085.0      2009-12     2009-12           1.0
1      13085.0      2009-12     2009-12           1.0
2      13085.0      2009-12     2009-12           1.0
3      13085.0      2009-12     2009-12           1.0
4      13085.0      2009-12     2009-12           1.0
5      13085.0      2009-12     2009-12           1.0
6      13085.0      2009-12     2009-12           1.0
7      13085.0      2009-12     2009-12           1.0
8      13085.0      2009-12     2009-12           1.0
9      13085.0      2009-12     2009-12           1.0

In [9]:
cohort_data = (
    df.groupby(["Cohort_Month", "Cohort_Index"])["Customer ID"]
      .nunique()
      .reset_index()
)

In [11]:
cohort_data.head(10)

  Cohort_Month  Cohort_Index  Customer ID
0      2009-12           1.0         1045
1      2009-12           2.0          392
2      2009-12           3.0          358
3      2009-12           4.0          447
4      2009-12           5.0          410
5      2009-12           6.0          408
6      2009-12           7.0          408
7      2009-12           8.0          374
8      2009-12           9.0          355
9      2009-12          10.0          392

In [13]:
cohort_matrix = cohort_data.pivot(
    index="Cohort_Month",
    columns="Cohort_Index",
    values="Customer ID"
)

In [15]:
cohort_matrix

Cohort_Index,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0
Cohort_Month,,,,,,,,,,,,,,,,,,,,,
2009-12,1045.0,392.0,358.0,447.0,410.0,408.0,408.0,374.0,355.0,392.0,...,319.0,273.0,316.0,303.0,287.0,274.0,332.0,319.0,427.0,83.0
2010-01,394.0,86.0,119.0,120.0,110.0,115.0,105.0,91.0,114.0,134.0,...,60.0,86.0,74.0,69.0,73.0,93.0,73.0,88.0,15.0,NaN
2010-02,363.0,109.0,82.0,110.0,93.0,76.0,79.0,103.0,100.0,106.0,...,74.0,67.0,61.0,53.0,85.0,90.0,62.0,11.0,NaN,NaN
2010-03,436.0,95.0,113.0,103.0,100.0,87.0,105.0,130.0,126.0,50.0,...,74.0,76.0,69.0,74.0,89.0,93.0,11.0,NaN,NaN,NaN
2010-04,291.0,67.0,58.0,47.0,54.0,67.0,79.0,76.0,33.0,34.0,...,43.0,41.0,41.0,50.0,61.0,7.0,NaN,NaN,NaN,NaN
2010-05,254.0,49.0,45.0,49.0,48.0,66.0,56.0,33.0,17.0,22.0,...,33.0,36.0,42.0,40.0,5.0,NaN,NaN,NaN,NaN,NaN
2010-06,269.0,58.0,53.0,55.0,62.0,76.0,35.0,25.0,22.0,32.0,...,33.0,37.0,55.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
2010-07,183.0,38.0,37.0,52.0,55.0,28.0,21.0,28.0,26.0,22.0,...,32.0,45.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-08,158.0,39.0,50.0,51.0,29.0,21.0,16.0,22.0,23.0,21.0,...,32.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-09,242.0,73.0,63.0,34.0,22.0,25.0,34.0,24.0,30.0,34.0,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-10,379.0,112.0,61.0,49.0,35.0,34.0,51.0,54.0,43.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-11,322.0,68.0,31.0,34.0,30.0,30.0,44.0,35.0,28.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-12,77.0,9.0,4.0,7.0,9.0,6.0,4.0,7.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-01,71.0,15.0,15.0,14.0,15.0,11.0,11.0,9.0,8.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-02,123.0,25.0,21.0,23.0,27.0,19.0,21.0,19.0,20.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-03,178.0,43.0,43.0,40.0,40.0,30.0,39.0,40.0,45.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-04,105.0,28.0,22.0,21.0,21.0,26.0,21.0,27.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-05,108.0,29.0,27.0,19.0,24.0,23.0,28.0,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-06,108.0,29.0,24.0,30.0,24.0,31.0,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07,102.0,24.0,31.0,30.0,36.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08,106.0,35.0,33.0,29.0,8.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09,187.0,64.0,73.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10,221.0,74.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-11,192.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
cohort_matrix.shape

(25, 25)

In [19]:
cohort_matrix.isnull().sum()

Cohort_Index
1.0      0
2.0      1
3.0      2
4.0      3
5.0      4
6.0      5
7.0      6
8.0      7
9.0      8
10.0     9
11.0    10
12.0    11
13.0    12
14.0    13
15.0    14
16.0    15
17.0    16
18.0    17
19.0    18
20.0    19
21.0    20
22.0    21
23.0    22
24.0    23
25.0    24
dtype: int64

In [21]:
cohort_data.head(10)

  Cohort_Month  Cohort_Index  Customer ID
0      2009-12           1.0         1045
1      2009-12           2.0          392
2      2009-12           3.0          358
3      2009-12           4.0          447
4      2009-12           5.0          410
5      2009-12           6.0          408
6      2009-12           7.0          408
7      2009-12           8.0          374
8      2009-12           9.0          355
9      2009-12          10.0          392

In [23]:
cohort_matrix.head()

Cohort_Index,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0
Cohort_Month,,,,,,,,,,,,,,,,,,,,,
2009-12,1045.0,392.0,358.0,447.0,410.0,408.0,408.0,374.0,355.0,392.0,...,319.0,273.0,316.0,303.0,287.0,274.0,332.0,319.0,427.0,83.0
2010-01,394.0,86.0,119.0,120.0,110.0,115.0,105.0,91.0,114.0,134.0,...,60.0,86.0,74.0,69.0,73.0,93.0,73.0,88.0,15.0,NaN
2010-02,363.0,109.0,82.0,110.0,93.0,76.0,79.0,103.0,100.0,106.0,...,74.0,67.0,61.0,53.0,85.0,90.0,62.0,11.0,NaN,NaN
2010-03,436.0,95.0,113.0,103.0,100.0,87.0,105.0,130.0,126.0,50.0,...,74.0,76.0,69.0,74.0,89.0,93.0,11.0,NaN,NaN,NaN
2010-04,291.0,67.0,58.0,47.0,54.0,67.0,79.0,76.0,33.0,34.0,...,43.0,41.0,41.0,50.0,61.0,7.0,NaN,NaN,NaN,NaN